#
# Copyright (c) 2019 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at:
#
#     https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

common:
  annotations:
    jkube.helm.sh/common: annotation
deployment:
  replicas: 1
  annotations:
    jkube.helm.sh/annotation-1: value-1
    jkube.helm.sh/annotation-2: value-2
service:
  annotations:
    api.service.kubernetes.io/path: /prod
