#
# Copyright (c) 2019 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at:
#
#     https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

version: 2

jobs:
  test:
    machine: true
    steps:
    - checkout
    - restore_cache:
        key: jkube-kit-{{ checksum "pom.xml" }}
    - run:
        command: |
          # Run maven build
          ./mvnw test verify -B -Pjacoco
          # Run codeocov analysis
          bash <(curl -s https://codecov.io/bash)
    - save_cache:
        key: jkube-kit-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2

  build:
    machine: true
    steps:
    - checkout
    - restore_cache:
        key: jkube-kit-{{ checksum "pom.xml" }}
    - run:
        command: |
          # Run maven build
          ./mvnw clean install
    - save_cache:
        key: jkube-kit-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2

  javadoc:
    machine: true
    steps:
    - checkout
    - restore_cache:
        key: jkube-kit-{{ checksum "pom.xml" }}
    - run:
        command: |
          # Run Maven build with javadoc jar generation
          ./mvnw clean install javadoc:jar -DskipTests -Pjavadoc
    - save_cache:
        key: jkube-kit-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2

  sonar:
    docker:
      - image: cimg/openjdk:11.0
    steps:
    - checkout
    - restore_cache:
        key: cachev1-jkube-kit-sonar-{{ checksum "pom.xml" }}
    - run: |
        MAVEN_OPTS="-Xmx3000m" ./mvnw -B -Pjacoco,sonar clean install
    - save_cache:
        key: cachev1-jkube-kit-sonar-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2

  sonar-pr:
    docker:
      - image: cimg/openjdk:11.0
    steps:
    - checkout
    - restore_cache:
        key: jkube-sonar-pr-{{ checksum "pom.xml" }}
    - run: |
        if [ -n "${CIRCLE_PR_NUMBER}" ]; then
          MAVEN_OPTS="-Xmx3000m" ./mvnw -B -Pjacoco,sonar clean install \
             -Dsonar.pullrequest.key=${CIRCLE_PR_NUMBER} \
             -Dsonar.pullrequest.branch=${CIRCLE_BRANCH} \
             -Dsonar.pullrequest.base=master
        else
          echo "No Sonar PR analysis as this is not a pull request"
        fi
    - save_cache:
        key: jkube-kit-sonar-pr-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2

  doc-preview-pr:
    docker:
      - image: cimg/openjdk:11.0
    steps:
    - checkout
    - restore_cache:
        key: jkube-kit-{{ checksum "pom.xml" }}
    - run: |
        if [ -n "${CIRCLE_PR_NUMBER}" ]; then
          ./scripts/generateDoc.sh
        else
          echo "No Doc preview run as this is not a pull request"
        fi
    - store_artifacts:
        path: ./docs-generated/

workflows:
  version: 2
  all:
    jobs:
    - build
    - javadoc
    - test
    - sonar-pr
    - sonar:
        filters:
          branches:
            only: master
    - doc-preview-pr
