#
# Copyright (c) 2019 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at:
#
#     https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
    - checkout
    - restore_cache:
        key: maven-test-{{ .Branch }}-{{ .Revision }}-{{ checksum "pom.xml" }}
    - run:
        command: |
          # Run maven build
          ./mvnw -B -Pjacoco clean install
          # Run codeocov analysis
          bash <(curl -s https://codecov.io/bash)
    - save_cache:
        key: maven-test-{{ .Branch }}-{{ .Revision }}-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2

  build:
    docker:
      - image: cimg/openjdk:8.0
    steps:
    - checkout
    - restore_cache:
        key: maven-build-{{ .Branch }}-{{ .Revision }}-{{ checksum "pom.xml" }}
    - run:
        command: |
          if [[ `javac -version 2>&1` == *"1.8.0"* ]]; then
            echo "Java 8 Present."
          else
            echo "Java 8 Not Present."
            exit 1
          fi
          # Run maven build
          ./mvnw clean install
    - save_cache:
        key: maven-build-{{ .Branch }}-{{ .Revision }}-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2

  sonar:
    docker:
      - image: cimg/openjdk:11.0
    steps:
    - checkout
    - restore_cache:
        key: maven-sonar-{{ .Branch }}-{{ .Revision }}-{{ checksum "pom.xml" }}
    - run: |
        MAVEN_OPTS="-Xmx3000m" ./mvnw -B -Pjacoco,sonar clean install
    - save_cache:
        key: maven-sonar-{{ .Branch }}-{{ .Revision }}-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2

  doc-preview-pr:
    docker:
      - image: cimg/openjdk:11.0
    steps:
    - checkout
    - run: |
        if [ -n "${CIRCLE_PULL_REQUEST}" ]; then
          ./scripts/generateDoc.sh
        else
          echo "No Doc preview run as this is not a pull request"
        fi
    - store_artifacts:
        path: ./docs-generated/

workflows:
  version: 2
  all:
    jobs:
    - build
    - test
    - sonar:
        filters:
          branches:
            only: master
    - doc-preview-pr
