#
# Copyright (c) 2019 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at:
#
#     https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

name: E2E Dispatch

on:
  pull_request:

jobs:
  dispatch-e2e-request:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          curl -X POST https://api.github.com/repos/jkubeio/ci/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --data '{"event_type": "pull_request", "client_payload": { "pr": "${{github.event.number}}" }}'
